name: Build Firmware

on:
  push:
    paths:
      - 'keyboards/rgbkb/sol3/keymaps/yarmek/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install qmk deps
        run: ./util/qmk_install.sh && python3 -m pip install qmk
      - name: Install git submodules
        run: make git-submodule
      - name: Compile firmware
        run: make rgbkb/sol3/rev1:yarmek
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v2
        with:
          name: RGBKB SOL3 QMK Firmware
          path: rgbkb_sol3_rev1_yarmek.bin
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rgbkb_sol3_rev1_yarmek.bin
