name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone YarmekQMK
        run: git clone https://github.com/Yarmek/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ./util/qmk_install.sh && python3 -m pip install qmk
      - name: Install git submodules
        run: cd qmk_firmware && make git-submodule
      - name: Compile firmware
        run: cd qmk_firmware && make rgbkb/sol3/rev1:yarmek
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v2
        with:
          name: RGBKB SOL3 QMK Firmware
          path: qmk_firmware/rgbkb_sol3_rev1-yarmek.bin
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qmk_firmware/rgbkb_sol3_rev1-yarmek.bin
