name: Build GMMK Pro Firmware

on:
  push:
    paths:
      - 'keyboards/gmmk/pro/ansi/keymaps/yarmek/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install qmk deps
        run: ./util/qmk_install.sh && python3 -m pip install qmk
      - name: Install git submodules
        run: make git-submodule
      - name: Compile firmware
        run: make gmmk/pro/ansi:yarmek
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v2
        with:
          name: RGBKB GMMK Pro QMK Firmware
          path: gmmk_pro_ansi_yarmek.bin
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gmmk_pro_ansi_yarmek.bin
